

# Get alertas

GET http://localhost:4000/api/v1/alerta

###

# Get alerta

GET http://localhost:4000/api/v1/alerta/1


###

# insert alerta

POST http://localhost:4000/api/v1/alerta/
Content-Type: application/json

{
    "usuario": 1,
    "ubicacion": {
        "latitud": "-34.59378016523937",
        "longitud": "-58.5908796490356"
    }
}

###

# Cerrar alerta
POST http://localhost:4000/api/v1/alerta/cierre
Content-Type: application/json

{
    "estado": "C",
    "id": 4
}