

# Get alertas

GET http://localhost:4000/api/v1/alerta

###

# Get alerta

GET http://localhost:4000/api/v1/alerta/4


###

# insert alerta

POST http://localhost:4000/api/v1/alerta/
Content-Type: application/json

{
    "usuario": 4,
    "ubicacion": {
        "latitud": "36.58403047386435",
        "longitud": "-4.555337180222222"
    }
}

###

# Cancelar alerta
POST http://localhost:4000/api/v1/alerta/cierre
Content-Type: application/json

{
    "estado": "C",
    "id": 29
}

###

# Solucionar alerta
POST http://localhost:4000/api/v1/alerta/cierre
Content-Type: application/json

{
    "estado": "S",
    "id": 25
}