

# Get alertas

#GET http://localhost:4000/api/v1/alerta
GET https://alertapersonaapi-testeo.up.railway.app/api/v1/alerta

###

# Get alerta

GET http://localhost:4000/api/v1/alerta/36


###

# insert alerta

POST http://localhost:4000/api/v1/alerta/
Content-Type: application/json

{
    "usuario": 4,
    "ubicacion": {
        "latitud": "-39.95153282559446",
        "longitud": "-71.07049904317019"
    }
}

###

# Cancelar alerta
# POST http://localhost:4000/api/v1/alerta/cierre
POST https://alertapersonaapi-testeo.up.railway.app/api/v1/alerta/cierre
Content-Type: application/json

{
    "estado": "C",
    "id": 52
}

###

# Solucionar alerta
POST http://localhost:4000/api/v1/alerta/cierre
Content-Type: application/json

{
    "estado": "S",
    "id": 25
}